version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: taskmanager_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./uploads:/usr/src/app/uploads

  pgadmin:
    image: dpage/pgadmin4
    container_name: taskmanager_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres

  storage:
    image: nginx:alpine
    container_name: taskmanager_storage
    ports:
      - "8081:80"
    volumes:
      - ./uploads:/usr/share/nginx/html/uploads

volumes:
  postgres_data:
